# Generated by Django 5.2.1 on 2025-07-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamslandapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
